### ISSUE TITLE
Is this required?

### ISSUE THREAD

**Issue by piggz** [sailfishos-chum/sailfishos-chum-gui-installer#1]
Just wondering, what is this required for? If chum is installed, the gui app is available.  The gui app is also available from the chumrpm site, so, wondering what this adds?

**Comment by Olf0** [comment]
It will make the awkward "chumrpm site" superfluous and resolve [sailfishos-chum-gui issue 96](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/96).

**Comment by piggz** [comment]
But, how will it be distributed?

**Comment by Olf0** [comment]
Here, at OpenRepos, wherever you want.  Crucial point is: It is an `noarch` RPM, hence the awkward selection (and any other user input) is not required any longer.  IMO a direct link to an RPM is way better than a web page in Rust where the user must select the correct RPM to download, which is infeasible if one does not know technical details as "CPU architecture" of ones SailfishOS device.

**Comment by Olf0** [comment]
Another way to look at the [sailfishos-chum-gui-installer](https://github.com/sailfishos-chum/sailfishos-chum-gui-installer) is as an extension of the current "[repository configuration RPM(s)](https://github.com/sailfishos-chum/main/tree/main/rpm)", which additionally downloads and installs the GUI app without any further user interaction after triggering the installation of the installer RPM.

I could have done that in the [sailfishos-chum/main](https://github.com/sailfishos-chum/main) source code repository, but as you can see at [the Storeman Installer source code repository](https://github.com/storeman-developers/harbour-storeman-installer/) it carries a shell script, some documentation etc. so it would clutter sailfishos-chum/main.  I also would like to keep the structure of the current master branch of Storeman Installer to copy things over here as a start, hence IMO a new repository is adequate.

**Comment by Olf0** [comment]
BTW @piggz, a few related questions WRT history and motivation(s):
1. Were the "[repository configuration RPM(s)](https://github.com/sailfishos-chum/main/tree/main/rpm)" originally intended to bootstrap the SailfishOS:Chum GUI application.  If so, I always misinterpreted their original purpose because the ["chumrpm site"](https://chumrpm.netlify.app/) did already exist, when I first looked at these repos.
2. OTOH I think they have lost that purpose (if it was one), because the "chumrpm site" superseded the "repository configuration RPM(s)" in this aspect.  Still people who do not want to use the GUI app (for whatever reason) and prefer `zypper` (or even `pkcon`:nauseated_face:) may use them (this was my interpretation of their purpose until today), right?
3. If my assumptions in 1 and 2 are correct, then the `Obsoletes: sailfishos-chum[-testing]` statements in the spec file of then GUI app have become superfluous, correct?  <sub>If so, this is still quite close to my original idea of them being misplaced.</sub>

**Comment by Olf0** [comment]
With 679 downloads of the SailfishOS:Chum GUI Installer versions 0.2.1 and 0.3.0 between 2023-01-28 (the date v0.2.1 was [uploaded at OpenRepos](https://openrepos.net/content/olf/sailfishoschum-gui-installer)) and 2023-02-13 (today), the answer to your question is obviously "Yes".
